spring:
  application:
    name: pix-boleto-kotlin
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments
    password: payments
  flyway:
    enabled: true
    locations: classpath:db/migration

resilience4j:
  retry:
    instances:
      bank-rail-provider:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
